---
- hosts: 172.31.18.81
  become: yes
  tasks:
  - include_tasks: myfile.yml
  - name: copy static files into ansible nodes
    copy:
       src: mytestfile
       dest: /home/ubuntu/mysaticfile
  - name: install webserver 
    apt:
      name: apache2
      state: present

  - name: copy dynamic files into ansible nodes
    template:
         src: myindex.j2
         dest: /var/www/html/index.html
        

  
