---
- hosts: all
  become: yes
  tasks: 
  - name: i want to install apache2 webserver on anible nodes
    apt:
      name: apache2
      state: present

  - name: i want to start webserver 
    service:
        name: apache2
        state: started
    